### ISSUE TITLE
Attribute Error: module 'tensorflow_datasets.core' has no attribute 'ReadWritePath'

### ISSUE THREAD

**Issue by shahpnmlab** [deepmind/tapnet#31]
Hi,
I am trying to run inference with a toy movie using the following command -
```(tapnet) pinot:$ python3 ./experiment.py   --config=./configs/tapnet_config.py   --jaxline_mode=eval_inference   --config.checkpoint_dir=./checkpoint/   --config.experiment_kwargs.config.inference.input_video_path=test_data/ta.mp4   --config.experiment_kwargs.config.inference.output_video_path=result.mp4   --config.experiment_kwargs.config.inference.resize_height=256   --config.experiment_kwargs.config.inference.resize_width=256   --config.experiment_kwargs.config.inference.num_points=20```
I have created a virtual conda environment and installed the deps using the requirements.txt file. Running the above command in the virtual env results in the following error -
```
2023-06-26 20:10:33.108623: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/home/pshah/software/tapnet/./experiment.py", line 32, in <module>
    from kubric.challenges.point_tracking import dataset
  File "/home/pshah/software/miniconda3/lib/python3.10/site-packages/kubric/__init__.py", line 20, in <module>
    from kubric.core.scene import Scene
  File "/home/pshah/software/miniconda3/lib/python3.10/site-packages/kubric/core/__init__.py", line 17, in <module>
    from .scene import Scene
  File "/home/pshah/software/miniconda3/lib/python3.10/site-packages/kubric/core/scene.py", line 20, in <module>
    from kubric.utils import next_global_count
  File "/home/pshah/software/miniconda3/lib/python3.10/site-packages/kubric/utils.py", line 52, in <module>
    from kubric.custom_types import PathLike
  File "/home/pshah/software/miniconda3/lib/python3.10/site-packages/kubric/custom_types.py", line 25, in <module>
    PathLike = Union[str, tfds.core.ReadWritePath]
AttributeError: module 'tensorflow_datasets.core' has no attribute 'ReadWritePath'
```
Is there a fix for this issue?
TIA!

**Comment by cdoersch** [comment]
Looks like tfds.core.ReadWritePath has been removed in recent versions of tfds, but Kubric hasn't been updated to deal with the change.  Crazily, it seems it was removed in https://github.com/tensorflow/datasets/commit/b25e2a27cfb630bec387b30d71510c350d6d9b48#diff-f6f15af3a15c244b2fe4273df8917f17debb279d192051d58b84b14568406fe1 all the way back in February last year; if you can roll back your tfds to before this change, then things should work.  But yeah, it looks like you should file a bug against kubric to get them to remove references to ReadWritePath.

**Comment by cdoersch** [comment]
Alternatively, running inference shouldn't actually depend on Kubric; you can probably remove references to Kubric in experiment.py and the rest should work.
